### ISSUE TITLE
Methode fcpoAddPayoneUserFlag() existiert nicht

### ISSUE THREAD

**Issue by fc-os** [PAYONE-GmbH/oxid-6#125]
Hi, 

In  der neuen Version 1.2.1 wird in der 
extend/application/models/fcPayOneOrder::_fcpoSetPayoneUserFlagsByAuthResponse() die Methode fcpoAddPayoneUserFlag() auf dem User Object ausgeführt, diese Methode gibt es aber nicht.

Es sieht aus als wenn ein unfertiges Feature gemerged wurde.

**Comment by FCStephanAltmann** [comment]
PR: https://github.com/PAYONE-GmbH/oxid-6/pull/126
Ticket: OX6-21
