### ISSUE TITLE
parent::finalizeOrder wird nicht aufgerufen

### ISSUE THREAD

**Issue by artvera** [PAYONE-GmbH/oxid-6#127]
Hi,

bei der Abarbeitung eines PayOne Bezahlprozesses wird anschließend nicht die parent::finalizeOrder aufgerufen. Was dazu führt das die Verarbeitungskette von Oxid unterbrochen wird und somit andere Module die die finalizeOrder überladen nicht aufgerufen werden. 

Klasse: fcPayOneOrder

**Comment by hreinberger** [comment]
Moin,

Wir haben vor ca. einem Jahr im Rahmen von #88 aufgrund dieses Issues im Oxid 5 Repo https://github.com/PAYONE-GmbH/oxid-5/issues/101 das Verhalten geändert, sollten jetzt aber im Oxid Standard sein. Wir mussten allerdings dafür sorgen, dass die finalizeOrder Methode unbedingt NICHT weiter ausgeführt, da das zu anderen Komplikationen führt. Allen voran, dass die Bestellung bereits abgeschlossen ist, wenn der parent gecallt wird.

Hast du ein konkretes Beispiel für uns, was dieses Verhalten kaputt macht? Dann schauen wir uns das nochmal an.

**Comment by artvera** [comment]
Hallo,

aktuell haben wir mehrere Module im Einsatz, die die finalizeOrder Methode der Klasse Order überladen um individuelle Aktionen nach Abschluss einer Bestellung auszuführen. Die nun durch den fehlenden parent Aufruf, wenn die Bezahlung über PayOne erfolgt, nicht mehr getriggert werden.

**Comment by hreinberger** [comment]
Verstehe. Ich nehme das nochmal mit und schaue, ob wir da was drehen können, ohne dass unsere eigenen Prozesse kaputt gehen. Ich melde mich bei Neuigkeiten wieder!

**Comment by hreinberger** [comment]
Hallo und ein frohes neues Jahr!

Wir sind zwischenzeitlich nochmal in uns gegangen und haben die Optionen nochmal abgewogen.
Da wir uns in dieser Methode an diversen Stellen einklinken und z. B. durch das optionale vorherige Speichern einer Bestellung sogar den Ablauf ändern, gestaltet sich eine vollständige Überladungstransparenz sehr schwer. 

Auf der Seite der Drittplugins wäre die Anpassung hingegen vermutlich einfacher. Hier müsste lediglich die gleiche Überladung in _fcpoFinalizeOrder durchgeführt werden, wie sie in finalizeOrder stattfindet. Mit einem Erweiterungsplugin, sollte sich das Ganze eleganter lösen lassen.

Wir sind natürlich keine Fans davon, mit unserem Plugin andere Plugins zu behindern, aber bei einem Plugin, das tief in die Shopprozesse eingreift (wie es ein Zahlungsplugin nunmal tut), können wir das manchmal nur schwer vermeiden. Insofern würden wir das Verhalten erstmal so belassen und euch darum bitten, über ein entsprechendes Erweiterungsplugin nachzudenken, das die Überladungen der finalizeOrder einfach auf fcpoFinalizeOrder anwendet.
