### ISSUE TITLE
Problem bei Adressübergabe aus Paypal Express

### ISSUE THREAD

**Issue by mzwack-norisk** [PAYONE-GmbH/oxid-6#154]
**Problem**: Durch den Split der aus Paypal übergebenen Adresse in `\fcPayOneOrderView::_fcpoSplitAddress` werden manche Straßen- und Hausnummernkombinationen nicht korrekt gesplittet.
Bei Straßennamen mit einem Leerzeichen (bspw. "Am Staudengarten 1") wird im aktuellen Code _keine_ Hausnummer extrahiert und der gesamte String als Straße verwendet.

**Modulversion**: 1.2.1 (und aktuelle Version)

**Comment by hreinberger** [comment]
Hi  @mzwack-norisk 
vielen Dank, schauen wir uns mal an!

**Comment by hreinberger** [comment]
Betroffene Codezeile: https://github.com/PAYONE-GmbH/oxid-6/blob/b9a691ddf78cb87f833d8451747035a814605e48/extend/application/controllers/fcPayOneOrderView.php#L718

**Comment by hreinberger** [comment]
fixed by #163
