### ISSUE TITLE
Wrong version in metadata 1.0.1 should be 1.0.2

### ISSUE THREAD

**Issue by stasiukaitis-saulius** [PAYONE-GmbH/oxid-6#16]
https://github.com/PAYONE-GmbH/oxid-6/blob/6b3934c8173a5a8bc29cd9e0a96251ff163eb662/metadata.php#L35

**Comment by fjbender** [comment]
Tagged a new version as well, to incorporate the changes from earlier pull requests, see https://github.com/PAYONE-GmbH/oxid-6/releases/tag/1.0.3
