### ISSUE TITLE
Problem with database default values (OXTIMESTAMP)

### ISSUE THREAD

**Issue by hkreuter** [PAYONE-GmbH/oxid-6#162]
When running OXID eshop 6.2 compilation tests (means running tests with compilation modules installed, tests are run for shop and for each module) there are  broken tests for shop and multiple modules when the PayOne module is around.
Looks like issues are caused by incorrect database default values for example

OXTIMESTAMP CHAR(32) COLLATE latin1_general_ci NOT NULL DEFAULT '',

Could you please have a look and fix this? If you need more information, feel free to contact me :)

**Comment by T-Kuchel** [comment]
Hi @hkreuter ,

we will check that and hopefully solve that issue.

Greetings from Kiel
Timo

**Comment by hreinberger** [comment]
This should also be fixed by #172

**Comment by swinde** [comment]
I can confirm this error for version 1.4.0
