### ISSUE TITLE
Probleme mit Oxid ERP-Schnittstelle bei PAYONE-Bestellungen

### ISSUE THREAD

**Issue by AlexHupe** [PAYONE-GmbH/oxid-6#180]
Beim Abruf der Aufträge mit PAYONE-Zahlungsarten kommt die Fehlermeldung: `Error on getting payone shop data: Can not find the requested plugin class.`

Vorkasse-Aufträge lassen sich abrufen. Gibt es noch eine plugin-Datei für die ERP-Schnittstelle speziell für PAYONE?

Danke für die Hilfe!

Alex

**Comment by AlexHupe** [comment]
Ich habe gerade gesehen, dass in der alten ERP-Schnittstelle für Oxid 4.x ein Plugin enthalten war: plugins/fcpayoneerpplugin.php Gibt es diese Datei auch für Oxid 6?

**Comment by fjbender** [comment]
Moin,

ich weiß leider nichts genaueres über die Datei und die alte ERP-Schnittstelle. Ich forsche mal nach und melde mich wieder.

**Comment by AlexHupe** [comment]
Hi, 

könnte sein, dass diese Datei tatsächlich von Efulfilment stammt. Sie stellt u.a. noch die Payment-ID zur Verfügung.

**Comment by fjbender** [comment]
Ich habe leider nichts weiter dazu gefunden. Wahrscheinlich müsste Efulfilment helfen.
