### ISSUE TITLE
Dutch translation delivers english values

### ISSUE THREAD

**Issue by kermie** [PAYONE-GmbH/oxid-6#182]
I :heart: that you tend to deliver Dutch translations for the front end. However, these translations contain values in English:
https://github.com/PAYONE-GmbH/oxid-6/blob/master/application/translations/nl/fcPayOne_lang.php

**Comment by fjbender** [comment]
We had a specific requirement for one payment method that we needed to provide certain texts in Dutch. However, due to nobody speaking Dutch we couldn't provide a full translation, and I am afraid that using Google Translate the translation will be too wonky to actually use.
