### ISSUE TITLE
Verkürzen der Zeit zwischen Reservierung und Capture

### ISSUE THREAD

**Issue by AlexHupe** [PAYONE-GmbH/oxid-6#200]
Hallo, 

wir haben bei den Zahlungsarten Kreditkarte und Paypal die Autorisierungsmethode: Autorisierung eingestellt, der Betrag soll sofort belastet werden. Nun gibt es zwischen der Reservierung und dem Zahlungseingang regelmäßig eine große Zeitspanne (bis zu 10 min), hier beispielhaft eine Paypal-Zahlung:

2020-11-24 08:42:58 Reservierung
2020-11-24 08:48:36 Zahlungseingang

In der Zwischenzeit holt jedoch oft unsere Wawi (Roqqio) die Aufträge ab und setzt sie auf den Status "unbezahlt". Wir müssen dann manuell den Zahlungseingang buchen. 

Lässt sich das Modul umstellen, so dass der Zahlungseingang schneller bzw. sofort nach Reservierung verbucht wird?

**Comment by fjbender** [comment]
Moin,

leider können wir den Eingang des Zahlungseinganges nicht immer schnell bestätigen. Für die Zahlungsarten PayPal und Kreditkarte kann aber eine Transaktion im Status Appointed als ausreichend sicher bezahlt angesehen werden.

Die Alternative wäre, den Zahlungsstatus Paid von Oxid an Roqqio über die [Transaktionsstatusweiterleitung](https://docs.payone.com/display/public/INT/Oxid+6+Extension#Oxid6Extension-Transactionstatusredirects) zu forwarden. Dies würde es aber nötig machen, dass Roqqio einen Endpunkt für diese Informationen zur Verfügung stellt.

**Comment by AlexHupe** [comment]
Hallo!

das ist schon einmal eine hilfreiche Aussage. Wir könnten also davon ausgehen, dass, wenn die Bestellung im Shop angelegt ist (egal ob Reservierung oder schon Zahlungseingang), sie mit großer Wahrscheinlichkeit bezahlt ist und verarbeitet werden kann? Habe ich das richtig vestanden?

**Comment by fjbender** [comment]
Sofern der Appointed-Status von uns eingegangen ist ja. In welchem Status die Bestellung dann ist hängt vom individuellen Mapping ab.

**Comment by AlexHupe** [comment]
Prima, vielen Dank für die Hilfe!
