### ISSUE TITLE
Paypal-Zahlung erfolgreich - keine Bestellung im Shop

### ISSUE THREAD

**Issue by AlexHupe** [PAYONE-GmbH/oxid-6#201]
Hallo, 

wir haben mit seit dem Update auf Oxid 6 ca. einmal wöchentlich den Fall, dass eine Paypalzahlung erfolgreich durchgeführt wurde, jedoch im Anschluss im Shop keine Bestellung angelegt wurde. Dieser Fehler wird erst bemerkt, wenn sich Kunden aktiv melden und nach einer Bestellbestätigung fragen. Hier ein aktuelles Beispiel:

Transaktionslog des Moduls: 
![transaktionen](https://user-images.githubusercontent.com/6893843/101137182-b2ac2400-360e-11eb-9e16-46e39f296e4c.png)

Bestellübersicht in diesem Zeitraum: 
![image](https://user-images.githubusercontent.com/6893843/101137032-7b3d7780-360e-11eb-8f8a-78ab11fc81b9.png)

Im Exception.log gibt es in diesem Zeitfenster keinen Eintrag. 

Wie kann man vorgehen, um den Fehler zu finden?

Vielen Dank!

**Comment by hreinberger** [comment]
Hi @AlexHupe 
hier kann es sein, dass es irgendwo in der Weiterleitungskette vom Shop zu PayPal und wieder zurück einen Abbruch gab und daher die Bestellung nicht korrekt angelegt werden konnte. Hier kann es helfen, den Haken "Bestellung vor Authorisierung speichern" in den PAYONE Zahlungseinstellungen zu setzen:
![grafik](https://user-images.githubusercontent.com/40197225/101145333-ee98b680-3619-11eb-9810-ded51d21c396.png)
Dadurch wird die Bestellung bereits während des Checkouts in einem unvollständigen Zustand gespeichert und eine Bestellnummer vergeben.

Hilft das nicht, melde dich bitte einmal bei unserem Tech Support unter tech.support[at]payone.com - die KollegInnen können dann gezielter in die Analyse einsteigen.

viele Grüße!
