### ISSUE TITLE
Wrong version in the module.

### ISSUE THREAD

**Issue by swinde** [PAYONE-GmbH/oxid-6#205]
Oxid Ecommerce Version 6.2.3 installs payone-gmbh / oxid-6 Version 3.0.1. Version 2.0.1 is output in the module!

**Comment by swinde** [comment]
Sorry for the confusion! I mean release 1.3.1 of course! See versions.txt there
OXID-eSales / oxideshop_metapackage_ce installed by default v1.3.1 in Oxid 6.2.3
Sorry for my Google English!

**Comment by fjbender** [comment]
Ah now I got it.

Oxid usually bundles a version that is a bit older, due to stability reasons. You should have no problem upgrading the module using composer: `composer require payone-gmbh/oxid-6:^1.4.0`

**Comment by swinde** [comment]
![oxmodules](https://user-images.githubusercontent.com/3349884/107036464-fca1b980-67b9-11eb-8e05-0e7b7bf5aa2a.jpg)

**Comment by swinde** [comment]
It is confusing if 1.3.1 is installed but 1.2.1 is output! 
See Release 1.3.1 here versions.txt

**Comment by swinde** [comment]
![version txt](https://user-images.githubusercontent.com/3349884/107037206-0bd53700-67bb-11eb-9116-a7531284d060.jpg)

**Comment by fjbender** [comment]
Ah, I see now. Yes, apparently there is a bug in version 1.3.1 where we didn't increase the version in the version.txt. So 1.3.1 still displays as 1.2.1, which is unfortunate.

However, this cannot be fixed now as the release tag can't be moved anymore. 1.4.0 is not affected by this bug anymore.
