### ISSUE TITLE
AmazonPay API Key rotation till 12.03.21 - Payone Plugin still working? - Urgent

### ISSUE THREAD

**Issue by jabommi** [PAYONE-GmbH/oxid-6#207]
Hello,

right now some merchants get a message, that they should change (rotate) their AmazonPay API Keys till 12.03.21?

When changing the keys, is the Oxid Payone Plugin still working with AmazonPay or does the merchant need to send the new keys to Payone, so Payone can put them into their configuration?

**Comment by fjbender** [comment]
Hi @jabommi,

When changing the Amazon API Keys, Amazon won't work anymore until the new keys are registered in your merchant account by our Merchant Service Team.

Please contact them to solve this issue.
