### ISSUE TITLE
ADD COLUMN `OXTIMESTAMP` missing from migrations for fcpocheckedaddresses 

### ISSUE THREAD

**Issue by TiiFuchs** [PAYONE-GmbH/oxid-6#237]
Found another issue with the migrations in 1.6.2:

https://github.com/PAYONE-GmbH/oxid-6/blob/c5c7973949ce3194b83195b45fd38facb169f351/core/fcpayone_events.php#L634

In this line the data from fcpo_checkdate gets copied to OXTIMESTAMP for the fcpocheckedaddresses table. But earlier in the migration this OXTIMESTAMP column never gets added. It's only in the CREATE TABLE, but if you migrate from an earlier version where the table already exists without OXTIMESTAMP it gets not created and therefore the copying e.t.c. does not work.

I had to create the column manually and deactivate and activate the module again for this to work.

**Comment by AlexHupe** [comment]
But there are many other differences between the tables for version 1.3.2 to 1.6.2. Is there a migration script?
