### ISSUE TITLE
Exception in v1.0.6

### ISSUE THREAD

**Issue by MantasVaitkunas** [PAYONE-GmbH/oxid-6#33]
Module version v1.0.6 is causing an exception when module is not yet active:
`OxidEsales\EshopCommunity\Tests\Unit\Application\Controller\Admin\ModuleListTest::testRender
OxidEsales\Eshop\Core\Exception\FileException: Requested file not found for module fcpayone (.../source/modules//payone_icon.png)`
This happens because of code in: https://github.com/PAYONE-GmbH/oxid-6/blob/master/metadata.php#L23
Ideally in metadata.php should not have any logic, only configuration.

**Comment by andrefatchip** [comment]
Hi Mantas :)

I removed this "make-up" code in Branch https://github.com/PAYONE-GmbH/oxid-6/tree/OXID-168 so this won't make any trouble anymore.

If you say no logic in metadata you're generally right of course but what should I do with this enterprise specific extend code?:
https://github.com/PAYONE-GmbH/oxid-6/blob/OXID-168/metadata.php#L236

Hope you get the need of having mechanisms for beeing able "extending only on edition x", so we could get rid of this kind of code in metadata. Will this code currently be causing exceptions anyway?

**Comment by MantasVaitkunas** [comment]
Hi @andrefatchip,
exceptions is not thrown anymore after removing "make up" code.
Regarding the logic in `metadata.php` file, you are right, in this case, it's necessary to have it.

BTW, small note, version in `metadata.php` is still 1.0.5.

**Comment by MantasVaitkunas** [comment]
Fixed with: https://github.com/PAYONE-GmbH/oxid-6/commit/3aaee398f219ef77a30e39df915eec946f4e34f4
