### ISSUE TITLE
Missing return statement in sendRequestConsumerScore

### ISSUE THREAD

**Issue by m-siddi** [PAYONE-GmbH/oxid-6#41]
To whom it may concern,

Our Dev team just discovered an error in the file fcporequest.php of the oxid-6 module in version 1.0.5. The error still exists in version 1.0.8 (line 1947):
![bildschirmfoto 2018-06-25 um 09 03 57 1](https://user-images.githubusercontent.com/35451901/41836969-8ef58fb4-785c-11e8-99d4-592217d0fffb.png)

The missing return statement leads to the shop ignoring the actual score value of the customer and using the fallback score value of 100 instead. Hence customers are not able to use invoice and credit card as payment method. Since a high percentage of customers prefer invoice, this is really an issue.

Do not hesitate to contact me in case of any questions you might have on this issue. Thank you!

Best regards,

Massimiliano Siddi

**Comment by rherwig** [comment]
Please let us know, if you require any aid / a PR for resolving the issue, since it is quite an impediment for us atm. I'll be glad to help out.

**Comment by rherwig** [comment]
There is a pull-request from 6 days ago. This is exactly the fix, that is required #46

**Comment by fjbender** [comment]
Yup, the task got re-assigned to another developer so they fixed it quicker than I though. It is currently in the QA processing and being checked for possible side effects, that shouldn't take too long though.

**Comment by m-siddi** [comment]
Dear fellow developers,

when will this fix be released, that is, when do you plan the next release? We would like to install the patch for our customer, and they are waiting some time for this fix.

Thank you very much!

Best regards,

Massimiliano
