### ISSUE TITLE
Fehlende payerror + payerrortext Variable

### ISSUE THREAD

**Issue by mzwack-norisk** [PAYONE-GmbH/oxid-6#43]
**Problem**: Wird man im Fehlerfall (bspw. nicht ausreichendes Guthaben) vom Paymentanbieter zurück in den Shop redirected, wird **keine** Fehlermeldung angezeigt.

**Ursache** ist, dass an der Stelle, an der die Error-URL zusammengebaut wird (`\fcpoRequest::_addRedirectUrls`), der von OXID erwartete Error-Parameter nicht angegeben wird.
fcPayone erwartet im Template (`out/blocks/fcpo_payment_errors.tpl`) den Errorcode –20 und den Fehlertext.
Damit eine Fehlermeldung angezeigt wird, müssen die Parameter `payerror` und `payerrortext` an die Error-URL angehängt werden.

**Modulversion**: alle (1.0.0 bis 1.0.8)

**Comment by fjbender** [comment]
Danke für den Hinweis, wir prüfen das!

OXID-197
