### ISSUE TITLE
bad compatibility with child themes

### ISSUE THREAD

**Issue by vanilla-thunder** [PAYONE-GmbH/oxid-6#48]
in ``out/blocks/fcpo_payment_select_override.tpl`` there is an if-else statement for choosing flow or azure templates:
````
[{if method_exists($oViewConf, 'getActiveTheme') && $oViewConf->getActiveTheme() == 'flow'}]
    [{assign var="sFcPoTemplatePath" value='flow'}]
[{else}]
    [{assign var="sFcPoTemplatePath" value='azure'}]
[{/if}]
````
The way its done, all flow child themes will get templates for azure. sincce their name is not "flow".

1) The best solution would be adding module setting and let customer pick wherever he wants flow or azure module templates. This will also work with 3rd party themes like roxive.

2) Another possible solution could be something like this: 
````
[{if method_exists($oViewConf, 'getActiveTheme') && $oViewConf->getActiveTheme()|strpos:'flow' !== false}]
    [{assign var="sFcPoTemplatePath" value='flow'}]
[{else}]
    [{assign var="sFcPoTemplatePath" value='azure'}]
[{/if}]
`````
This way at least all themes that contain "flow" in their names will get flow templates (since many people name their child themes something like "flow"+"shop name")

You should also apply this fix to the module for oxid v4/v5.
I also would like to mention, that there is no azure in v6 anymore and this code is actually obsolete.

cheers

**Comment by fjbender** [comment]
Thanks for your feedback. We'll think of a (hopefully) clever way to handle this better.

**Comment by fjbender** [comment]
@vanilla-thunder We already fixed this in our Oxid 5 plugin and ported the solution to Oxid 6. Can you confirm #52 fixes this issue?

**Comment by vanilla-thunder** [comment]
looks good to me

**Comment by fjbender** [comment]
Thanks! :)
