### ISSUE TITLE
Missing return statement not released yet

### ISSUE THREAD

**Issue by rherwig** [PAYONE-GmbH/oxid-6#59]
Hey everyone,

PR #46 has still not been released and unfortunately our customers are still waiting for a fix. When can we expect this fix to be released?

@fjbender 
@m-siddi

**Comment by fjbender** [comment]
We'll release today, tomorrow the latest.

**Comment by fjbender** [comment]
It's done: https://github.com/PAYONE-GmbH/oxid-6/releases/tag/1.0.9

Thanks for your patience and support!
